const fs = require('node:fs');
const path = require('node:path');
const test = require('node:test');
const assert = require('node:assert/strict');

const ROOT = path.resolve(__dirname, '..');
const read = (relativePath) => fs.readFileSync(path.join(ROOT, relativePath), 'utf8');

test('android ASR build script and project exist', () => {
  const pkg = JSON.parse(read('3rd/tts-server/package.json'));
  assert.match(pkg.scripts['build:android-asr'], /android-asr/);
  assert.equal(fs.existsSync(path.join(ROOT, '3rd/tts-server/android-asr/app/build.gradle.kts')), true);
});

test('android ASR package declares required offline model and HTTP permissions', () => {
  const build = read('3rd/tts-server/android-asr/app/build.gradle.kts');
  const manifest = read('3rd/tts-server/android-asr/app/src/main/AndroidManifest.xml');
  assert.match(build, /model\.int8\.onnx/);
  assert.match(build, /tokens\.txt/);
  assert.match(build, /arm64-v8a/);
  assert.match(manifest, /RECORD_AUDIO/);
  assert.match(manifest, /BLUETOOTH_CONNECT/);
  assert.match(manifest, /MODIFY_AUDIO_SETTINGS/);
  assert.match(manifest, /INTERNET/);
});

test('android ASR UI and HTTP endpoints are present', () => {
  const build = read('3rd/tts-server/android-asr/app/build.gradle.kts');
  const layout = read('3rd/tts-server/android-asr/app/src/main/res/layout/activity_main.xml');
  const main = read('3rd/tts-server/android-asr/app/src/main/java/com/aasc/asr/MainActivity.kt');
  const recorder = read('3rd/tts-server/android-asr/app/src/main/java/com/aasc/asr/AudioRecorder.kt');
  const stats = read('3rd/tts-server/android-asr/app/src/main/java/com/aasc/asr/AudioCaptureStats.kt');
  const chart = read('3rd/tts-server/android-asr/app/src/main/java/com/aasc/asr/VolumeChartView.kt');
  const envelope = read('3rd/tts-server/android-asr/app/src/main/java/com/aasc/asr/AudioVolumeEnvelope.kt');
  const inputDevice = read('3rd/tts-server/android-asr/app/src/main/java/com/aasc/asr/AudioInputDevice.kt');
  const sco = read('3rd/tts-server/android-asr/app/src/main/java/com/aasc/asr/BluetoothScoController.kt');
  const voiceprintModel = read('3rd/tts-server/android-asr/app/src/main/java/com/aasc/asr/VoiceprintModel.kt');
  const server = read('3rd/tts-server/android-asr/app/src/main/java/com/aasc/asr/AsrHttpServer.kt');
  const page = read('3rd/tts-server/android-asr/app/src/main/java/com/aasc/asr/AsrWebPage.kt');
  const strings = read('3rd/tts-server/android-asr/app/src/main/res/values/strings.xml');
  assert.match(layout, /recordButton/);
  assert.match(layout, /recordControlOverlay/);
  assert.match(layout, /audioVolumeChart/);
  assert.match(layout, /FrameLayout/);
  assert.match(layout, /selectAudioButton/);
  assert.match(layout, /recognizeButton/);
  assert.match(layout, /resultText/);
  assert.match(layout, /cpuModeSpinner/);
  assert.match(layout, /audioInputSpinner/);
  assert.match(layout, /refreshAudioInputButton/);
  assert.match(layout, /audioInputStatus/);
  assert.match(layout, /voiceprintStatus/);
  assert.match(layout, /voiceprintModelSpinner/);
  assert.match(layout, /voiceprintPrecisionSpinner/);
  assert.match(layout, /speakerName/);
  assert.match(layout, /asrDenoise/);
  assert.match(layout, /voiceprintDenoise/);
  assert.match(layout, /registerSpeaker/);
  assert.match(layout, /testSingle/);
  assert.match(layout, /testMulti/);
  assert.match(layout, /testMultiFast/);
  assert.match(layout, /speakerCount/);
  assert.match(layout, /voiceprintResult/);
  assert.match(main, /asrDenoise/);
  assert.match(main, /voiceprintDenoise/);
  assert.match(main, /voiceprintCoordinator\.register/);
  assert.match(main, /voiceprintCoordinator\.test/);
  assert.match(main, /VoiceprintSpeakerCount\.parse/);
  assert.match(main, /VoiceprintUiRequest\.create/);
  assert.match(main, /UiStatus\.voiceprintResult/);
  assert.match(main, /reloadVoiceprintVariant/);
  assert.match(main, /AudioInputDevice\.enumerate/);
  assert.match(main, /BLUETOOTH_CONNECT/);
  assert.match(recorder, /start\(preferredDevice: AudioDeviceInfo\? = null\)/);
  assert.match(recorder, /candidate\.setPreferredDevice\(preferredDevice\)/);
  assert.match(recorder, /BLUETOOTH_SCO_WIDEBAND_SAMPLE_RATE = 16000/);
  assert.match(recorder, /BLUETOOTH_SCO_NARROWBAND_SAMPLE_RATE = 8000/);
  assert.match(recorder, /AudioSource\.VOICE_COMMUNICATION/);
  assert.match(recorder, /录音启动后无法保持所选麦克风路由/);
  assert.match(recorder, /AudioResampler\.resampleMono/);
  assert.match(recorder, /recordingState != AudioRecord\.RECORDSTATE_RECORDING/);
  assert.match(recorder, /AudioRecord\.READ_BLOCKING/);
  assert.match(recorder, /captureStats\(\)/);
  assert.match(recorder, /routedDevice/);
  assert.match(recorder, /capturedVolumeEnvelope/);
  assert.match(recorder, /AudioVolumeEnvelope\.fromPcm16/);
  assert.match(stats, /volumeEnvelope/);
  assert.match(main, /audioVolumeChart\.setVolumePoints/);
  assert.match(chart, /class VolumeChartView/);
  assert.match(chart, /drawPath/);
  assert.match(envelope, /DEFAULT_WINDOW_SAMPLES/);
  assert.match(inputDevice, /GET_DEVICES_INPUTS/);
  assert.match(inputDevice, /TYPE_BLUETOOTH_SCO/);
  assert.match(inputDevice, /BACK_MIC_ADDRESS/);
  assert.match(inputDevice, /preferredDefault/);
  assert.match(sco, /startBluetoothSco/);
  assert.match(sco, /ACTION_SCO_AUDIO_STATE_UPDATED/);
  assert.match(sco, /isBluetoothScoOn = true/);
  assert.match(sco, /isBluetoothScoOn = false/);
  assert.match(sco, /SCO_AUDIO_STATE_ERROR/);
  assert.match(main, /switchVoiceprintVariantFromHttp/);
  assert.match(main, /R\.string\.http_ready/);
  assert.match(strings, /name="http_ready"/);
  assert.match(voiceprintModel, /ERES2NET_BASE/);
  assert.doesNotMatch(voiceprintModel, /ERES2NET_LARGE|ERES2NET_V2|INT8/);
  assert.match(build, /3dspeaker_speech_eres2net_base_sv_zh-cn_3dspeaker_16k\.onnx/);
  assert.match(build, /pyannote_segmentation_3_0_int8\.onnx/);
  assert.doesNotMatch(build, /eres2net_base_sv_zh-cn_3dspeaker_16k_int8|eres2net_large|eres2netv2/);
  assert.doesNotMatch(page, /eres2net-large|eres2netv2|value="int8"/);
  assert.match(server, /"\/health"/);
  assert.match(server, /"\/api\/asr"/);
  assert.match(server, /val route = request\.path\.substringBefore/);
  assert.match(server, /request\.method == "GET" && \(route == "\/" \|\| route == "\/index\.html"\)/);
  assert.match(server, /18080/);
  assert.match(server, /"\/api\/voiceprint\/model"/);
  assert.match(page, /fetch\('\/api\/asr\?/);
  assert.match(page, /type="file"/);
  assert.match(page, /getUserMedia/);
  assert.match(page, /AudioContext/);
  assert.match(page, /录音/);
  assert.match(page, /id="voiceprintModel"/);
  assert.match(page, /id="voiceprintPrecision"/);
  assert.match(page, /\/api\/voiceprint\/model/);
  assert.match(page, /precision/);
});
